tienda/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add', views.add, name='add'),
    path('remove', views.remove, name='remove'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('users/login', views.login_view, name='login'),
    path('users/logout', views.logout_view, name='logout'),
    path('users/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('addresses/', include('shipping_addresses.urls')),
    path('codes/', include('promo_codes.urls')),
    path('billing/', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/carts/models.py
from django.db import models

from users.models import User
from products.models import Product
from orders.common import OrderStatus

from django.db.models.signals import pre_save, post_save, m2m_changed

import uuid
import decimal


class Cart(models.Model):
    cart_id = models.CharField(
        max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True,
                             on_delete=models.CASCADE)  # uno a muchos
    products = models.ManyToManyField(Product, through='CartProducts')  # muchos a muchos
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05

    def __str__(self):
        return f'{self.user}: {self.cart_id}'

    def update_subtotal(self):
        # self.subtotal = sum([product.price for product in self.products.all()])
        self.subtotal = sum([
            cart_product.product.price * cart_product.quantity for cart_product in self.products_related()
        ])
        self.save()

    def update_total(self):
        self.total = self.subtotal + \
            (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def update_totals(self):
        self.update_subtotal()
        self.update_total()
        
        if self.order:
            self.order.update_total()
        
        # order = self.order_set.first() #_set accede a la relación
        # if order:
        #     order.update_total()
    
    def products_related(self):
        return self.cartproducts_set.select_related('product')
    
    def has_products(self):
        return self.products.exists()
    
    @property
    def order(self):
        #return self.order_set.first()
        return self.order_set.filter(status=OrderStatus.CREATED).first()


class CartProductsManager(models.Manager):
    
    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)
        
        if not created:
            quantity = object.quantity + int(quantity)
        
        object.update_quantity(quantity)
        
        return object


class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    
    objects = CartProductsManager()
    
    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())


def update_totals(sender, instance, action, *args, **kwargs):
    actions = ['post_add', 'post_remove', 'post_clear']
    if action in actions:
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

tienda/carts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from products.models import Product

from .models import Cart, CartProducts
from .utils import get_or_create_cart


def cart(request):
    # Crear una sesión
    # request.session['cart_id'] = '123'

    # Obtener sesión
    # session = request.session.get('cart_id')
    # print(f'session: {session}')

    # Eliminar sesión
    # request.session['cart_id'] = None
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {
        'cart': cart,
    })


def add(request):
    cart = get_or_create_cart(request)
    # product = Product.objects.get(pk=request.POST.get('product_id'))
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = request.POST.get('quantity', 1)
    
    # cart.products.add(product, through_defaults={
    #     'quantity': quantity,
    # })
    
    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, 
                                                                  product=product, 
                                                                  quantity=quantity)
    
    return render(request, 'carts/add.html', {
        'product': product,
        'quantity': quantity,
    })


def remove(request):
    cart = get_or_create_cart(request)
    # product = Product.objects.get(pk=request.POST.get('product_id'))
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    cart.products.remove(product)
    return redirect('carts:cart')

tienda/carts/templates/carts/snippets/add.html
<form method="post" action="{% url 'carts:add' %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <div class="row g-3 align-items-center">
        <div class="col-auto">
            <button id="remove" type="button" class="form-control btn btn-info">-</button>
        </div>
        <div class="col-3">
            <input id="quantity" name="quantity" type="number" value="1" class="form-control text-center"
                min="1" required>
        </div>
        <div class="col-auto">
            <button id="add" type="button" class="form-control btn btn-info">+</button>
        </div>
    </div>
    <div class="mt-2">
        <button type="submit" class="btn btn-warning">
            <i class="fa-solid fa-cart-plus"></i>
            Agregar al carrito
        </button>
    </div>
</form>

<script>
    const add = document.getElementById('add');
    const remove = document.getElementById('remove');
    const quantity = document.getElementById('quantity');

    add.addEventListener('click', function() {
        quantity.value = parseInt(quantity.value) + 1;
    });

    remove.addEventListener('click', function() {
        value = parseInt(quantity.value)
        if (value > 1) {
            value--;
        }
        quantity.value = value;
    });

</script>

tienda/carts/templates/carts/snippets/remove.html
<form method="post" action="{% url 'carts:remove' %}">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <button type="submit" class="btn btn-link text-secondary p-0">
        <i class="fa-solid fa-square-minus text-danger"></i>
        Quitar
    </button>
</form>