tienda/billing_profiles/urls.py
from django.urls import path

from . import views

app_name = 'billing_profiles'

urlpatterns = [
    path('', views.BillingProfileListView.as_view(), name='billing_profiles'),
    path('add', views.add, name='add'),
]

tienda/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add', views.add, name='add'),
    path('remove', views.remove, name='remove'),
]

tienda/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('address', views.address, name='address' ),
    path('select/address', views.select_address, name='select_address'),
    path('set/address/<int:pk>', views.check_address, name='set_address'),
    path('payment', views.payment, name='payment'),
    path('confirm', views.confirm, name='confirm'),
    path('cancel', views.cancel, name='cancel'),
    path('complete', views.complete, name='complete'),
    path('completed', views.OrderListView.as_view(), name='completed'),
]

tienda/shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('new', views.new, name='new'),
    path('update/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('users/login', views.login_view, name='login'),
    path('users/logout', views.logout_view, name='logout'),
    path('users/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('addresses/', include('shipping_addresses.urls')),
    path('codes/', include('promo_codes.urls')),
    path('billing/', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% if stripe_public_key %}
    <meta name="stripe_public_key" content="{{ stripe_public_key }}">
    {% endif %}
    {% block css %}
    {% endblock %}
    <title>{{ title }}</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% include 'messages.html' %}
        {% block breadcrumb %}
        {% endblock %}
        <div class="row mt-3">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/16bd4938d9.js" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock %}
</body>
</html>

tienda/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col">
    <h4 class="text-center">{{ message }}</h4>
    {% include 'products/snippets/search.html' %}
    {# Listar productos object_list product_list #}
    <div class="mt-3">
        <ul class="pagination">
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}" >
                <a href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }} {% endif %}" class="page-link">Anterior</a>
            </li>
            {% for page in paginator.page_range %}
            <li class="page-item">
                <a href="?page={{ page }}" class="page-link {% if page_obj.number == page %} active {% endif %}">{{ page }}</a>
            </li>
            {% endfor %}
            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}" >
                <a href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }} {% endif %}" class="page-link">Siguiente</a>
            </li>
        </ul>
    </div>
    <div class="row ">
        {% include 'products/snippets/list.html' %}
    </div>
    {% if is_paginated %}
    
    {% endif %}
    {# <img src="{% static 'img/mochila.png' %}" alt="Mochila bonita"> #}
</div>
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

tienda/templates/messages.html
{% if messages %}
    {% for message in messages %}
    {# <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}"></div> #}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endfor %}
{% endif %}

tienda/templates/navbar.html
{% url 'index' as index %}
{% url 'register' as register %}
{% url 'login' as login %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completed' as completed %}
{% url 'billing_profiles:billing_profiles' as billing_profiles  %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ index }}">La Tienda</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == index %}active{% endif %}" href="{{ index }}">
                        <i class="fa-solid fa-house"></i>
                        Inicio
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == cart %}active{% endif %}" href="{{ cart }}">
                        <i class="fa-solid fa-cart-shopping"></i>
                        Carrito
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == shipping_addresses %}active{% endif %}" href="{{ shipping_addresses }}">
                        <i class="fa-solid fa-map-location-dot"></i>
                        Direcciones
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == completed %}active{% endif %}" href="{{ completed }}">
                        <i class="fa-solid fa-truck-fast"></i>
                        Pedidos
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == billing_profiles %}active{% endif %}" href="{{ billing_profiles }}">
                        <i class="fa-solid fa-credit-card"></i>
                        Métodos de pago
                    </a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav me-2">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link ms-auto" href="{% url 'logout' %}">
                        <i class="fa-solid fa-right-to-bracket"></i>
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    {# <a class="nav-link ms-auto" href="{% url 'register' %}"> #}
                        <a class="nav-link ms-auto {% if request.path == register %}active{% endif %}"
                            href="{{ register }}">
                            <i class="fa-solid fa-user-plus"></i>
                            Registro
                        </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ms-auto {% if request.path == login %}active{% endif %}" href="{{ login }}">
                        <i class="fa-solid fa-user"></i>
                        Login
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>