tienda/carts/urls.py
from django.urls import path

from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add', views.add, name='add'),
    path('remove', views.remove, name='remove'),
]

tienda/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('address', views.address, name='address' ),
    path('select/address', views.select_address, name='select_address'),
    path('set/address/<int:pk>', views.check_address, name='set_address'),
    path('payment', views.payment, name='payment'),
    path('confirm', views.confirm, name='confirm'),
    path('cancel', views.cancel, name='cancel'),
    path('complete', views.complete, name='complete'),
    path('completed', views.OrderListView.as_view(), name='completed'),
]

tienda/promo_codes/urls.py
from django.urls import path

from . import views

app_name = 'promo_codes'

urlpatterns = [
    path('validate', views.validate, name='validate'),
]

tienda/shipping_addresses/urls.py
from django.urls import path

from . import views

app_name = 'shipping_addresses'

urlpatterns = [
    path('', views.ShippingAddressListView.as_view(), name='shipping_addresses'),
    path('new', views.new, name='new'),
    path('update/<int:pk>', views.ShippingAddressUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.ShippingAddressDeleteView.as_view(), name='delete'),
    path('default/<int:pk>', views.default, name='default'),
]

tienda/tienda/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('users/login', views.login_view, name='login'),
    path('users/logout', views.logout_view, name='logout'),
    path('users/register', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('cart/', include('carts.urls')),
    path('order/', include('orders.urls')),
    path('addresses/', include('shipping_addresses.urls')),
    path('codes/', include('promo_codes.urls')),
    path('billing/', include('billing_profiles.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/orders/models.py
from django.db import models
from django.db.models.signals import pre_save

import uuid
import decimal

from users.models import User
from carts.models import Cart
from shipping_addresses.models import ShippingAddress
from promo_codes.models import PromoCode
from billing_profiles.models import BillingProfile

from .common import OrderStatus, choices

class Order(models.Model):
    order_id = models.CharField(max_length=100,
                                null=False,
                                blank=False,
                                unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50,
                              choices=choices,
                              default=OrderStatus.CREATED)
    shipping_total = models.DecimalField(default=5,
                                         max_digits=8,
                                         decimal_places=2)
    total = models.DecimalField(default=0,
                                max_digits=8,
                                decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress, 
                                         null=True, 
                                         blank=True, 
                                         on_delete=models.CASCADE)
    promo_code = models.OneToOneField(PromoCode, 
                                      null=True, 
                                      blank=True, 
                                      on_delete=models.CASCADE)
    billing_profile = models.ForeignKey(BillingProfile, 
                                        null=True, 
                                        blank=True, 
                                        on_delete=models.CASCADE)

    def get_total(self):
        return self.cart.total + self.shipping_total - decimal.Decimal(self.get_discount())
    
    def get_discount(self):
        if self.promo_code:
            return self.promo_code.discount
        
        return 0
    
    def update_total(self):
         self.total = self.get_total()
         self.save()
    
    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)
        
        return shipping_address
    
    def get_or_set_billing_profile(self):
        if self.billing_profile:
            return self.billing_profile
        
        billing_profile = self.user.billing_profile
        if billing_profile:
            self.update_billing_profile(billing_profile)
            
        return billing_profile
    
    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()
    
    def update_billing_profile(self, billing_profile):
        self.billing_profile = billing_profile
        self.save()
        
    def cancel(self):
        self.status = OrderStatus.CANCELED
        self.save()
    
    def complete(self):
        self.status = OrderStatus.COMPLETED
        self.save()
        
    def apply_promo_code(self, promo_code):
        if self.promo_code is None:
            self.promo_code = promo_code
            self.save()
            
            self.update_total()
            promo_code.use()
            
    @property
    def description(self):
        return f'Compra de {self.cart.products.count()} productos'

    def __str__(self):
        return f'{self.user.username} {self.order_id}'


def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())


def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()


pre_save.connect(set_order_id, Order)
pre_save.connect(set_total, Order)

tienda/orders/views.py
import threading

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.db.models.query import EmptyQuerySet
from django.db import transaction

from shipping_addresses.models import ShippingAddress

from carts.utils import get_or_create_cart, destroy_cart
from .utils import get_or_create_order, breadcrumb, destroy_order

from .mails import Mail
from .decorators import validate_cart_and_order

from charges.models import Charge

class OrderListView(LoginRequiredMixin, ListView):
    login_url = 'login'
    template_name = 'orders/orders.html'
    
    def get_queryset(self):
        #return EmptyQuerySet
        return self.request.user.orders_completed()


@login_required(login_url='login')
@validate_cart_and_order
def order(request, cart, order):
    # cart = get_or_create_cart(request)
    # order = get_or_create_order(cart=cart, request=request)
    
    if not cart.has_products():
        return redirect('carts:cart')

    return render(request, 'orders/order.html', {
        'cart': cart,
        'order': order,
        'breadcrumbs': breadcrumb(),
    })


@login_required(login_url='login')
@validate_cart_and_order
def address(request, cart, order):
    # cart = get_or_create_cart(request)
    # order = get_or_create_order(cart, request)
    
    if not cart.has_products():
        return redirect('carts:cart')

    shipping_address = order.get_or_set_shipping_address()
    # has_multiple_addresses = request.user.shippingaddress_set.count() > 1
    has_multiple_addresses = request.user.has_multiple_addresses

    return render(request, 'orders/address.html', {
        'cart': cart,
        'order': order,
        'breadcrumbs': breadcrumb(address=True),
        'shipping_address': shipping_address,
        'has_multiple_addresses': has_multiple_addresses,
    })


@login_required(login_url='login')
def select_address(request):
    # shipping_addresses = request.user.shippingaddress_set.all()
    shipping_addresses = request.user.addresses

    return render(request, 'orders/select_address.html', {
        'breadcrumbs': breadcrumb(address=True),
        'shipping_addresses': shipping_addresses,
    })


@login_required(login_url='login')
@validate_cart_and_order
def check_address(request, cart, order, pk):
    # cart = get_or_create_cart(request)
    # order = get_or_create_order(cart, request)

    shipping_address = get_object_or_404(ShippingAddress, pk=pk)

    if request.user.id != shipping_address.user_id:
        return redirect('carts:cart')

    order.update_shipping_address(shipping_address)

    return redirect('orders:address')

@login_required(login_url='login')
@validate_cart_and_order
def payment(request, cart, order):
    
    if not cart.has_products() or order.shipping_address is None:
        return redirect('carts:cart')
    
    billing_profile = order.get_or_set_billing_profile()
    
    return render(request, 'orders/payment.html', {
        'cart': cart,
        'order': order,
        'billing_profile': billing_profile,
        'breadcrumbs': breadcrumb(address=True, payment=True)
    })

@login_required(login_url='login')
@validate_cart_and_order
def confirm(request, cart, order):
    # cart = get_or_create_cart(request)
    # order = get_or_create_order(cart, request)
    
    if not cart.has_products() or order.shipping_address is None or order.billing_profile is None:
        return redirect('carts:cart')

    shipping_address = order.shipping_address
    if shipping_address is None:
        return redirect('orders:address')

    return render(request, 'orders/confirm.html', {
        'cart': cart,
        'order': order,
        'shipping_address': shipping_address,
        'breadcrumbs': breadcrumb(address=True, payment=True, confirmation=True),
    })


@login_required(login_url='login')
@validate_cart_and_order
def cancel(request, cart, order):
    # cart = get_or_create_cart(request)
    # order = get_or_create_order(cart, request)

    if request.user.id != order.user_id:
        return redirect('carts:cart')

    order.cancel()

    destroy_cart(request)
    destroy_order(request)

    messages.warning(request, 'Orden cancelada')
    return redirect('index')

@login_required(login_url='login')
@validate_cart_and_order
def complete(request, cart, order):
    # cart = get_or_create_cart(request)
    # order = get_or_create_order(cart, request)
    
    if request.user.id != order.user_id:
        return redirect('carts:cart')
    
    charge = Charge.objects.create_charge(order)
    
    if charge:
        with transaction.atomic():
            order.complete()
        
            # Habilitar para enviar correo de confirmación
            # Mail.send_complete_order(order, request.user)
            
            # Habilitar para enviar correo de confirmación async
            # thread = threading.Thread(target=Mail.send_complete_order, args=(
            #     order, request.user
            # ))
            # thread.start()
        
            destroy_cart(request)
            destroy_order(request)
            
            messages.success(request, 'Compra completada exitosamente')
    else:
        messages.warning(request, 'Pago no autorizado')
    
    return redirect('index')

tienda/orders/templates/orders/address.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col">
    {% if shipping_address %}
    <div class="h3">
        Recoge el pedido en el punto de entrega
    </div>
    <div>
        {% include 'shipping_addresses/snippets/shipping_address.html' %}
        <div class="mt-2">
            <a href="{% url 'orders:payment' %}" class="btn btn-info">Entregar a esta dirección</a>
        </div>        
        {% if has_multiple_addresses %}
        <div class="mt-2">
            <a href="{% url 'orders:select_address' %}">Seleccionar otra dirección</a>
        </div>
        {% endif %}
    </div>
    {% else %}
    <div class="h3">
        Registra tu dirección de envío
    </div>
    <div>
        {% url 'orders:address' as next_url %}
        <a href="{% url 'shipping_addresses:new' %}?next={{ next_url }}">Nueva dirección de envío</a>        
    </div>
    {% endif %}
</div>
{% endblock %}

tienda/orders/templates/orders/confirm.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col-8">
    <div class="h3">
        Confirma tu pedido
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <div class="fw-bold">
                        Dirección de envío
                    </div>
                    <div class="card-text">
                        {{ shipping_address.address }}
                    </div>
                    <div class="card-text">
                        {{ shipping_address.line1 }}
                    </div>
                    <div class="card-text">
                        {{ shipping_address.reference }}
                    </div>
                    <div class="card-text">
                        {{ shipping_address.zipcode }}
                    </div>
                </div>
                <div class="col-4">
                    <div class="fw-bold">
                        Método de pago
                    </div>
                    <div class="card-text">
                        Tarjeta terminación {{ order.billing_profile.last4 }}
                    </div>
                </div>
                <div class="col-4">
                    <div class="fw-bold">
                        Código promocional
                    </div>
                    <form id="promocode-form" action="{% url 'promo_codes:validate' %}">
                        <input type="text" name="code" value="{{ order.promo_code.code  }}" 
                            class="form-control" placeholder="Código" 
                            {% if order.promo_code  %} readonly {% endif %}>
                    </form>
                    <div id="promocode-success" class="text-success" style="font-size: 14px;">
                        {% if order.promo_code %}
                        Código aplicado exitosamente
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="mt-3">
        <div class="card">
            <div class="card-body">
                {% for product in cart.products.all %}
                    {% include 'orders/snippets/product.html' %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="col">
    {% url 'orders:complete' as next_url %}
    {% include 'orders/snippets/summary.html' with next_url=next_url %}
    <div class="mt-3">
        <a href="{% url 'orders:cancel' %}" class="btn btn-danger">Cancelar orden</a>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    const form = document.getElementById('promocode-form')

    form.addEventListener('submit', function(e){
        e.preventDefault();
        const input = this.code;
        const code = input.value;
        const url = this.action + '?code=' + code;
        const div_total = document.getElementById('order-total');
        const div_success = document.getElementById('promocode-success');
        
        fetch(url).then(
            response => response.json()
        ).then( 
            response => {
                if (response.status === true) {
                    div_total.innerHTML = '$' + response.total;
                    div_success.innerHTML = 'Código aplicado exitosamente';
                    div_success.classList.remove('text-danger');
                    div_success.classList.add('text-success');
                    input.readOnly = true;
                } else {
                    div_success.innerHTML = 'Código no válido';
                    div_success.classList.remove('text-success');
                    div_success.classList.add('text-danger');
                }
            }
        );
    });

</script>
{% endblock %}

tienda/orders/templates/orders/order.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col-8">
    <h3>Revisa tu pedido</h3>
    <div class="card">
        <div class="card-body">
            {% for product in cart.products.all %}
                {% include 'orders/snippets/product.html' %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="col">
    {% url 'orders:address' as next_url %}
    {% include 'orders/snippets/summary.html' with next_url=next_url %}
</div>
{% endblock %}

tienda/orders/templates/orders/orders.html
{% extends 'base.html' %}

{% block content %}
<div class="col">
    <div class="h3">Mis pedidos</div>
    <div>
        {% for order in object_list %}
            {% include 'orders/snippets/order.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

tienda/orders/templates/orders/payment.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col">
    <div class="h3">
        Método de pago
    </div>
    <div>
        {% include 'billing_profiles/snippets/billing_profile.html' %}
    </div>
    <div class="mt-3">
        <a href="{% url 'orders:confirm' %}" class="btn btn-info">Confirmar</a>
    </div>
</div>
{% endblock %}

tienda/orders/templates/orders/select_address.html
{% extends 'base.html' %}

{% block breadcrumb %}
    {% include 'orders/snippets/breadcrumb.html' %}
{% endblock %}

{% block content %}
<div class="col">
    <div class="h3">
        Selecciona un dirección de envío
    </div>
    <div class="mt-3">
        {% for shipping_address in shipping_addresses %}
        <div class="card mt-2">
            <div class="card-body">
                <h5 class="card-title">{{ shipping_address.address }}</h5>
                <p class="card-title">{{ shipping_address.zipcode }}</p>
                <a href="{% url 'orders:set_address' shipping_address.pk %}" class="btn btn-info">Seleccionar</a>
            </div>
        </div>        
        {% endfor %}
    </div>
</div>
{% endblock %}